version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=linktrackerDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d linktrackerDB" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:

